-- MySQL Script generated by MySQL Workbench
-- Mon May 30 21:51:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appounting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appounting` ;

-- -----------------------------------------------------
-- Schema appounting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appounting` DEFAULT CHARACTER SET utf8 ;
USE `appounting` ;

-- -----------------------------------------------------
-- Table `appounting`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`usuario` ;

CREATE TABLE IF NOT EXISTS `appounting`.`usuario` (
  `user` VARCHAR(80) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `pin` INT(4) NULL,
  PRIMARY KEY (`user`),
  UNIQUE INDEX `email_UNIQUE` (`email`));


-- -----------------------------------------------------
-- Table `appounting`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `appounting`.`cuenta` (
  `numero_cuenta` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE(9,2) NOT NULL,
  `usuario_user` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`numero_cuenta`),
  INDEX `fk_cuenta_usuario_idx` (`usuario_user`),
  CONSTRAINT `fk_cuenta_usuario`
    FOREIGN KEY (`usuario_user`)
    REFERENCES `appounting`.`usuario` (`user`));


-- -----------------------------------------------------
-- Table `appounting`.`deudas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`deudas` ;

CREATE TABLE IF NOT EXISTS `appounting`.`deudas` (
  `referencia` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto_total` DOUBLE(9,2) NOT NULL,
  `monto_restante` DOUBLE(9,2) NOT NULL,
  `cant_cuotas` INT NOT NULL,
  `cant_cuotas_restantes` INT NOT NULL,
  `fecha_limite_pago` DATE NULL,
  `estado` ENUM("PAGADO", "NO PAGADO") NOT NULL,
  `descripcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_deudas_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_deudas_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`ahorros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`ahorros` ;

CREATE TABLE IF NOT EXISTS `appounting`.`ahorros` (
  `referencia` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `monto_total` DOUBLE(9,2) NOT NULL,
  `monto_actual` DOUBLE(9,2) NULL,
  `descripcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_ahorros_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_ahorros_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `appounting`.`transaccion` (
  `referencia` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `tipo` TINYINT NOT NULL,
  `fecha` DATE NOT NULL,
  `detalles` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_transaccion_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_transaccion_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `appounting`.`prestamos` (
  `referencia` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto_total` DOUBLE(9,2) NOT NULL,
  `monto_restante` DOUBLE(9,2) NULL,
  `cantidad_cuotas` INT NOT NULL,
  `cuotas_restantes` INT NULL,
  `descipcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_prestamos_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_prestamos_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`sesiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`sesiones` ;

CREATE TABLE IF NOT EXISTS `appounting`.`sesiones` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` VARCHAR(30) NOT NULL,
  `fecha_fin` VARCHAR(30) NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `fk_sesiones_cuenta1_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_sesiones_cuenta1`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
