-- MySQL Script generated by MySQL Workbench
-- Sat May 14 10:36:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appounting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appounting` ;

-- -----------------------------------------------------
-- Schema appounting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appounting` DEFAULT CHARACTER SET utf8 ;
USE `appounting` ;

-- -----------------------------------------------------
-- Table `appounting`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`usuario` ;

CREATE TABLE IF NOT EXISTS `appounting`.`usuario` (
  `usuario` VARCHAR(80) NOT NULL,
  `cedula` INT NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula`),
  UNIQUE INDEX `email_UNIQUE` (`email`));


-- -----------------------------------------------------
-- Table `appounting`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `appounting`.`cuenta` (
  `numero_cuenta` INT NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `usuario_usuario` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`numero_cuenta`),
  INDEX `fk_cuenta_usuario_idx` (`usuario_usuario`),
  CONSTRAINT `fk_cuenta_usuario`
    FOREIGN KEY (`usuario_usuario`)
    REFERENCES `appounting`.`usuario` (`usuario`));


-- -----------------------------------------------------
-- Table `appounting`.`deudas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`deudas` ;

CREATE TABLE IF NOT EXISTS `appounting`.`deudas` (
  `referencia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `fecha_limite_pago` DATE NOT NULL,
  `cant_cuotas` INT NOT NULL,
  `descripcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_deudas_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_deudas_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`ahorros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`ahorros` ;

CREATE TABLE IF NOT EXISTS `appounting`.`ahorros` (
  `referencia` INT NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `monto` DOUBLE(9,1) NOT NULL,
  `descripcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_ahorros_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_ahorros_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`transaccion` ;

CREATE TABLE IF NOT EXISTS `appounting`.`transaccion` (
  `referencia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `tipo` VARCHAR(80) NOT NULL,
  `fecha` DATE NOT NULL,
  `detalles` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_transaccion_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_transaccion_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `appounting`.`prestamos` (
  `referencia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `cuotas` INT NOT NULL,
  `descipcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_prestamos_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_prestamos_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


-- -----------------------------------------------------
-- Table `appounting`.`gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appounting`.`gastos` ;

CREATE TABLE IF NOT EXISTS `appounting`.`gastos` (
  `referencia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `monto` DOUBLE(9,2) NOT NULL,
  `descipcion` TEXT NULL,
  `cuenta_numero_cuenta` INT NOT NULL,
  PRIMARY KEY (`referencia`),
  INDEX `fk_gastos_cuenta_idx` (`cuenta_numero_cuenta`),
  CONSTRAINT `fk_gastos_cuenta`
    FOREIGN KEY (`cuenta_numero_cuenta`)
    REFERENCES `appounting`.`cuenta` (`numero_cuenta`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
